alias lt='ls -latr'
alias ll='ls -l'
alias la='ls -a'
alias cls='clear'
alias gs='git status'
alias chrome='open -a /Applications/Google\ Chrome.app'
alias repath='source $HOME/.path'
alias domysql='sudo /usr/local/mysql/bin/mysqld_safe --user=mysql'
